"""Execution-layer tests: EIP-712 signing pipeline + order builder safety.

The signing vector below was generated by the production SoDEX trading
client and verified bit-for-bit — if the pipeline here ever drifts from
that implementation, these tests fail.
"""
from __future__ import annotations

import pytest

from edgework.exchange.constants import NETWORK_CONFIG, OrderSide
from edgework.exchange.order_builder import (
    ClosePlan,
    plan_close_from_position,
    simulate,
)
from edgework.exchange.signing import derive_address, sign_action

# Throwaway key used only for deterministic test vectors.
TEST_PK = "a" * 64
CHAIN_ID = NETWORK_CONFIG["mainnet"]["chain_id"]

PARAMS = {
    "accountID": 12345,
    "symbolID": 1,
    "orders": [{
        "clOrdID": "12345-edgework-1700000000000",
        "modifier": 1,
        "side": 2,
        "type": 2,
        "timeInForce": 3,
        "reduceOnly": True,
        "positionSide": 1,
        "quantity": "0.5",
    }],
}

# Reference vector from the production implementation (verified 2026-06).
EXPECTED_DIGEST = "0xcd357eb0501404eba67475fe49a4dca41525fb230bb9883d9ee9ef22abfe2a70"
EXPECTED_SIG = (
    "0x011c305b19beee11a5b4f1960a7b4afbb7e54a5c4e34f10066c30cfe10b2c"
    "2c6920e1a862ac68d11c62fd85a3d59b8e123cd1bb48489e3d2f7d21f53131df6bd7400"
)


def test_signature_matches_production_vector():
    s = sign_action("newOrder", PARAMS, TEST_PK, CHAIN_ID, nonce_ms=1700000000000)
    assert s.digest == EXPECTED_DIGEST
    assert s.typed_signature == EXPECTED_SIG


def test_signature_deterministic_and_wire_format():
    s1 = sign_action("newOrder", PARAMS, TEST_PK, CHAIN_ID, nonce_ms=1700000000000)
    s2 = sign_action("newOrder", PARAMS, TEST_PK, CHAIN_ID, nonce_ms=1700000000000)
    assert s1.typed_signature == s2.typed_signature
    assert s1.typed_signature.startswith("0x01")
    assert len(s1.typed_signature) == 134  # 0x01 + r(64) + s(64) + v(2)


def test_derive_address_checksummed():
    addr = derive_address(TEST_PK)
    assert addr.startswith("0x") and len(addr) == 42
    assert addr == derive_address("0x" + TEST_PK)  # 0x prefix tolerated


def test_unknown_order_field_rejected():
    bad = dict(PARAMS)
    bad["orders"] = [dict(PARAMS["orders"][0], bogusField=1)]
    with pytest.raises(ValueError, match="Unknown fields"):
        sign_action("newOrder", bad, TEST_PK, CHAIN_ID)


# ── ClosePlan safety properties ─────────────────────────────────────────────

def test_long_position_closes_via_sell():
    plan = plan_close_from_position(
        {"symbol": "BTC-USD", "side": "long", "size": 0.5},
        symbol_id=1, account_id=12345,
        reason="contrarian_to_smart_money",
    )
    assert plan.close_side == OrderSide.SELL


def test_short_position_closes_via_buy_with_abs_qty():
    plan = plan_close_from_position(
        {"symbol": "ETH-USD", "side": "short", "size": -2.0},
        symbol_id=2, account_id=12345,
    )
    assert plan.close_side == OrderSide.BUY
    assert plan.quantity == "2"


def test_close_order_is_always_reduce_only():
    plan = plan_close_from_position(
        {"symbol": "BTC-USD", "side": "long", "size": 0.5},
        symbol_id=1, account_id=12345,
    )
    _, params = plan.to_order_params()
    assert params["orders"][0]["reduceOnly"] is True


def test_close_plan_requires_account_id():
    plan = ClosePlan(
        symbol="BTC-USD", symbol_id=1, position_side="long",
        quantity="1", reason="manual_close",
    )
    with pytest.raises(ValueError, match="account_id"):
        plan.to_order_params()


# ── Simulation mode ─────────────────────────────────────────────────────────

def test_simulate_signs_but_never_sends():
    sim = simulate("newOrder", PARAMS, network="mainnet")
    assert sim.sent is False
    assert sim.body["signature"].startswith("0x01")
    assert sim.body["params"]["orders"][0]["reduceOnly"] is True
    assert set(sim.body.keys()) == {"type", "params", "nonce", "signature"}


def test_simulate_uses_fresh_ephemeral_key_each_call():
    a = simulate("newOrder", PARAMS)
    b = simulate("newOrder", PARAMS)
    assert a.ephemeral_signer != b.ephemeral_signer
